---
type: opt # single|window, maybe add opt
key: ii_rnn #added to the csv names
evaluation: evaluation_user_based #evaluation|evaluation_last|evaluation_multiple|evaluation_user_based|evaluation_user_based_multiple
data:
  name: xing #added in the end of the csv names
  folder: data/xing/xing2016/prepared/
  prefix: interactions
  type: hdf #hdf (if there is no type, the default is csv)

results:
  folder: results/opt/xing/ii_rnn/

metrics:
- class: accuracy_multiple.Precision
  length: [5,10,15,20]
- class: accuracy_multiple.Recall
  length: [5,10,15,20]
- class: accuracy_multiple.MAP
  length: [5,10,15,20]
- class: accuracy.HitRate
  length: [5,10,15,20]
- class: accuracy.MRR
  length: [5,10,15,20]


optimize:
  class: accuracy.MRR
  length: [20]
  iterations: 100 #optional

algorithms:
- class: IIRNN.ii_rnn.IIRNN
  params: {} # batch_size: 50
  params_opt:
    dropout_pkeep: {from: 0.1, to: 1.0, in: 10, type: float}
    learning_rate: [ {from: 0.1, to: 0.01, in: 10, type: float32}, {from: 0.5, to: 0.1, in: 5, type: float32} ]
    st_internal_size: [50, 100] # [50]
    max_session_representation: [1, 5, 10, 15, 20]
  key: ii_rnn